# Infrastructure Contracts
# Owner: DEVOPS | Consumers: ALL
# Last Updated: 2026-01-14
#
# This file documents ALL infrastructure requirements.
# - Environment variables needed for each environment
# - Resource requirements
# - Health check specifications
# - Secrets management
# - Automation scripts

version: "1.0"

# =============================================================================
# ENVIRONMENTS
# =============================================================================

environments:
  development:
    description: Local development environment
    variables:
      required:
        NODE_ENV:
          value: development
          description: Runtime environment
        DATABASE_URL:
          description: PostgreSQL connection string
          example: postgres://user:pass@localhost:5432/app_dev
        JWT_SECRET:
          description: Secret for signing JWT tokens (min 32 chars)
          example: development-secret-at-least-32-chars
      optional:
        PORT:
          default: "3000"
          description: API server port
        LOG_LEVEL:
          default: debug
          description: Logging verbosity
        CORS_ORIGIN:
          default: "http://localhost:5173"
          description: Allowed CORS origin

  staging:
    description: Pre-production testing environment
    variables:
      required:
        NODE_ENV:
          value: staging
        DATABASE_URL:
          secret: true
          description: PostgreSQL connection string
        JWT_SECRET:
          secret: true
          minLength: 64
        REDIS_URL:
          secret: true
          description: Redis for session/cache
      optional:
        LOG_LEVEL:
          default: info
        SENTRY_DSN:
          description: Error tracking

  production:
    description: Live production environment
    variables:
      required:
        NODE_ENV:
          value: production
        DATABASE_URL:
          secret: true
        JWT_SECRET:
          secret: true
          minLength: 64
          rotation: monthly
        REDIS_URL:
          secret: true
      optional:
        LOG_LEVEL:
          default: warn
        SENTRY_DSN:
          description: Error tracking
        RATE_LIMIT_MAX:
          default: "100"
          description: Requests per minute per IP

# =============================================================================
# SERVICES
# =============================================================================

services:
  api:
    description: Backend API service
    port: 3000
    healthCheck:
      endpoint: /health
      interval: 30s
      timeout: 5s
      retries: 3
      successCodes: [200]
    resources:
      development:
        memory: 512MB
        cpu: 0.5
      production:
        memory: 1GB
        cpu: 1
        replicas: 2
    dependencies:
      - postgres
      - redis

  app:
    description: Frontend web application
    port: 80
    healthCheck:
      endpoint: /
      interval: 30s
      timeout: 5s
    resources:
      production:
        memory: 128MB
        cpu: 0.25

  postgres:
    description: PostgreSQL database
    port: 5432
    image: postgres:16-alpine
    healthCheck:
      command: pg_isready -U postgres
      interval: 10s
      timeout: 5s
    resources:
      production:
        memory: 2GB
        storage: 100GB
    backup:
      frequency: daily
      retention: 30d

  redis:
    description: Redis cache/session store
    port: 6379
    image: redis:7-alpine
    healthCheck:
      command: redis-cli ping
      interval: 10s
    resources:
      production:
        memory: 512MB

# =============================================================================
# HEALTH CHECKS
# =============================================================================

healthChecks:
  api:
    endpoint: GET /health
    expectedResponse:
      status: healthy
      checks:
        database: connected
        redis: connected
    alertOn:
      - status != healthy
      - responseTime > 1000ms
      - consecutiveFailures >= 3

  liveness:
    endpoint: GET /health/live
    description: Is the process running?
    timeout: 3s

  readiness:
    endpoint: GET /health/ready
    description: Is the service ready to accept traffic?
    timeout: 5s
    checks:
      - database connection
      - redis connection
      - migrations applied

# =============================================================================
# NETWORKING
# =============================================================================

networking:
  domains:
    production:
      api: api.example.com
      app: app.example.com
    staging:
      api: api.staging.example.com
      app: staging.example.com

  ssl:
    provider: letsencrypt
    autoRenew: true
    minVersion: TLSv1.2

  rateLimit:
    enabled: true
    windowMs: 60000
    max: 100
    skipSuccessfulRequests: false
    keyGenerator: ip

# =============================================================================
# DEPLOYMENT
# =============================================================================

deployment:
  strategy: rolling
  maxUnavailable: 1
  maxSurge: 1
  
  preDeployChecks:
    - migrations pending check
    - database backup verified
    - rollback procedure documented
    
  postDeployChecks:
    - health endpoint returns 200
    - smoke tests pass
    - error rate < 1%
    
  rollback:
    automatic: true
    trigger:
      - error rate > 5%
      - health check failures >= 3
      - latency p99 > 2s
    procedure: |
      1. Stop new deployment
      2. Scale down new pods
      3. Scale up previous version
      4. Verify health checks
      5. Notify team

# =============================================================================
# SECRETS MANAGEMENT
# =============================================================================

secrets:
  storage: environment-variables
  rotation:
    JWT_SECRET:
      frequency: monthly
      gracePeriod: 7d
    DATABASE_PASSWORD:
      frequency: quarterly
  
  neverLog:
    - JWT_SECRET
    - DATABASE_URL
    - API_KEYS
    - *_PASSWORD
    - *_SECRET

# =============================================================================
# MONITORING
# =============================================================================

monitoring:
  metrics:
    - http_requests_total
    - http_request_duration_seconds
    - database_connections_active
    - database_query_duration_seconds
    
  alerts:
    - name: HighErrorRate
      condition: error_rate > 5%
      severity: critical
      
    - name: SlowResponses
      condition: p99_latency > 2s
      severity: warning
      
    - name: DatabaseConnectionPoolExhausted
      condition: db_connections >= max_connections * 0.9
      severity: critical

  logging:
    format: json
    fields:
      - timestamp
      - level
      - message
      - requestId
      - userId
      - duration

# =============================================================================
# AUTOMATION SCRIPTS
# =============================================================================

scripts:
  # Project management
  create-project:
    path: scripts/create-project.sh
    description: Create a new project in sandbox/ from base-project template
    usage: "./create-project.sh <project-name>"
    outputs:
      - sandbox/<project-name>/            # Project directory
      - sandbox/<project-name>/.project.yaml  # Project metadata
      - sandbox/.registry.yaml             # Updated registry

  # Task execution
  execute-task:
    path: scripts/execute-task.sh
    description: Execute a single task (validates deps, acquires locks, updates status)
    usage: "./execute-task.sh <path-to-task.yaml>"
    behavior:
      - Validates task file exists and has required fields
      - Checks all dependencies are completed
      - Acquires file locks for task files
      - Updates task status to in_progress
      - Logs execution start in progress section

  execute-phase:
    path: scripts/execute-phase.sh
    description: Execute all tasks in a phase in parallel
    usage: "./execute-phase.sh <feature-dir> <phase-number>"
    behavior:
      - Finds all tasks in specified phase
      - Filters to pending/blocked tasks
      - Checks dependencies for each
      - Executes eligible tasks in parallel
      - Reports which tasks started/blocked

  # Lock management
  acquire-lock:
    path: scripts/acquire-lock.sh
    description: Acquire file locks for a task
    usage: "./acquire-lock.sh <task-file> [ttl-minutes]"
    config:
      default_ttl: 30
      max_ttl: 120
      lock_file: sandbox/.locks.yaml
    behavior:
      - Creates lock entries in .locks.yaml
      - Checks for existing conflicting locks
      - Supports TTL-based automatic expiry
      - Queues requests for locked files

  release-lock:
    path: scripts/release-lock.sh
    description: Release file locks for a task
    usage: "./release-lock.sh <task-file> [reason]"
    reasons:
      - task_completed
      - task_failed
      - manual
      - expired
    behavior:
      - Removes lock entries from .locks.yaml
      - Moves released locks to history section
      - Notifies about queued requests

  # Index management
  update-index:
    path: scripts/update-index.sh
    description: Regenerate index files after task/feature changes
    usage: |
      ./update-index.sh --feature <feature-dir>
      ./update-index.sh --project <project-dir>
      ./update-index.sh --dashboard
      ./update-index.sh --all
    outputs:
      - <feature>/index.yaml           # Feature task index
      - <project>/plans/features/.index.yaml  # Project feature index
      - sandbox/.dashboard.yaml        # Dashboard aggregation
    regenerates:
      - Task counts by status
      - Tasks by phase and agent
      - Dependency graph
      - Progress percentages

  update-registry:
    path: scripts/update-registry.sh
    description: Manage sandbox/.registry.yaml with project list
    usage: |
      ./update-registry.sh --scan              # Scan and sync
      ./update-registry.sh --add <project-dir> # Add project
      ./update-registry.sh --remove <name>     # Remove project
      ./update-registry.sh --status <name> <status>  # Update status
      ./update-registry.sh --list              # List projects
    statuses:
      - active
      - paused
      - archived
      - failed

  # Existing scripts
  verify-contracts:
    path: scripts/verify-contracts.sh
    description: Verify implementation matches contract specifications
    checks:
      - Contract files exist
      - No hardcoded design values
      - TypeScript compilation
      - Linting rules

  check-workflow:
    path: scripts/check-workflow.sh
    description: Check workflow status and readiness

  post-check:
    path: scripts/post-check.sh
    description: Post-commit verification checks

# =============================================================================
# FILE STORAGE SCHEMA
# =============================================================================

fileStorage:
  description: File-based task/project storage for Claude Code multi-agent framework

  directories:
    sandbox:
      path: sandbox/
      description: Container for all spawned projects
      files:
        - .registry.yaml    # Global project registry
        - .dashboard.yaml   # Cross-project metrics
        - .locks.yaml       # Active file locks

    project:
      path: sandbox/<project>/
      description: Individual project directory
      files:
        - .project.yaml     # Project metadata
      subdirs:
        - plans/features/   # Feature directories
        - contracts/        # Contract files
        - api/              # Backend code
        - dashboard/        # Frontend code
        - scripts/          # Automation scripts

    feature:
      path: sandbox/<project>/plans/features/<FEAT-XXX>/
      description: Feature directory with tasks
      files:
        - feature.yaml      # Feature metadata
        - index.yaml        # Task index
        - README.md         # Feature documentation
      subdirs:
        - tasks/            # Task YAML files

  schemas:
    task:
      required:
        - id              # TASK-XXX format
        - feature_id      # Parent feature ID
        - title           # Task title
        - agent           # Assigned agent
        - status          # pending|in_progress|blocked|qa|completed
        - priority        # high|medium|low
        - phase           # Execution phase number
        - created_at      # ISO8601 timestamp
        - updated_at      # ISO8601 timestamp
        - depends_on      # List of dependency task IDs
        - blocks          # List of tasks this blocks
        - instructions    # Agent instructions

    feature:
      required:
        - id              # FEAT-XXX format
        - slug            # URL-friendly name
        - title           # Feature title
        - status          # planning|in_progress|qa|completed|archived
        - priority        # high|medium|low
        - phases          # Execution phase definitions

    project:
      required:
        - id              # proj_XXXXXXXX format
        - name            # Project name
        - status          # active|paused|archived|failed
        - created_at      # ISO8601 timestamp

  locking:
    config:
      default_ttl_minutes: 30
      max_ttl_minutes: 120
      auto_release_on_completion: true
    lock_types:
      exclusive: "Only one owner can modify"
      shared: "Multiple readers allowed"
    conflict_resolution:
      - "Higher phase tasks yield to lower phase"
      - "Same phase: first-come-first-served"
      - "QA tasks have priority over new features"
