# Infrastructure Contracts
# Owner: DEVOPS | Consumers: ALL
# Last Updated: [DATE]
#
# This file documents ALL infrastructure requirements.
# - Environment variables needed for each environment
# - Resource requirements
# - Health check specifications
# - Secrets management

version: "1.0"

# =============================================================================
# ENVIRONMENTS
# =============================================================================

environments:
  development:
    description: Local development environment
    variables:
      required:
        NODE_ENV:
          value: development
          description: Runtime environment
        DATABASE_URL:
          description: PostgreSQL connection string
          example: postgres://user:pass@localhost:5432/app_dev
        JWT_SECRET:
          description: Secret for signing JWT tokens (min 32 chars)
          example: development-secret-at-least-32-chars
      optional:
        PORT:
          default: "3000"
          description: API server port
        LOG_LEVEL:
          default: debug
          description: Logging verbosity
        CORS_ORIGIN:
          default: "http://localhost:5173"
          description: Allowed CORS origin

  staging:
    description: Pre-production testing environment
    variables:
      required:
        NODE_ENV:
          value: staging
        DATABASE_URL:
          secret: true
          description: PostgreSQL connection string
        JWT_SECRET:
          secret: true
          minLength: 64
        REDIS_URL:
          secret: true
          description: Redis for session/cache
      optional:
        LOG_LEVEL:
          default: info
        SENTRY_DSN:
          description: Error tracking

  production:
    description: Live production environment
    variables:
      required:
        NODE_ENV:
          value: production
        DATABASE_URL:
          secret: true
        JWT_SECRET:
          secret: true
          minLength: 64
          rotation: monthly
        REDIS_URL:
          secret: true
      optional:
        LOG_LEVEL:
          default: warn
        SENTRY_DSN:
          description: Error tracking
        RATE_LIMIT_MAX:
          default: "100"
          description: Requests per minute per IP

# =============================================================================
# SERVICES
# =============================================================================

services:
  api:
    description: Backend API service
    port: 3000
    healthCheck:
      endpoint: /health
      interval: 30s
      timeout: 5s
      retries: 3
      successCodes: [200]
    resources:
      development:
        memory: 512MB
        cpu: 0.5
      production:
        memory: 1GB
        cpu: 1
        replicas: 2
    dependencies:
      - postgres
      - redis

  app:
    description: Frontend web application
    port: 80
    healthCheck:
      endpoint: /
      interval: 30s
      timeout: 5s
    resources:
      production:
        memory: 128MB
        cpu: 0.25

  postgres:
    description: PostgreSQL database
    port: 5432
    image: postgres:16-alpine
    healthCheck:
      command: pg_isready -U postgres
      interval: 10s
      timeout: 5s
    resources:
      production:
        memory: 2GB
        storage: 100GB
    backup:
      frequency: daily
      retention: 30d

  redis:
    description: Redis cache/session store
    port: 6379
    image: redis:7-alpine
    healthCheck:
      command: redis-cli ping
      interval: 10s
    resources:
      production:
        memory: 512MB

# =============================================================================
# HEALTH CHECKS
# =============================================================================

healthChecks:
  api:
    endpoint: GET /health
    expectedResponse:
      status: healthy
      checks:
        database: connected
        redis: connected
    alertOn:
      - status != healthy
      - responseTime > 1000ms
      - consecutiveFailures >= 3

  liveness:
    endpoint: GET /health/live
    description: Is the process running?
    timeout: 3s

  readiness:
    endpoint: GET /health/ready
    description: Is the service ready to accept traffic?
    timeout: 5s
    checks:
      - database connection
      - redis connection
      - migrations applied

# =============================================================================
# NETWORKING
# =============================================================================

networking:
  domains:
    production:
      api: api.example.com
      app: app.example.com
    staging:
      api: api.staging.example.com
      app: staging.example.com

  ssl:
    provider: letsencrypt
    autoRenew: true
    minVersion: TLSv1.2

  rateLimit:
    enabled: true
    windowMs: 60000
    max: 100
    skipSuccessfulRequests: false
    keyGenerator: ip

# =============================================================================
# DEPLOYMENT
# =============================================================================

deployment:
  strategy: rolling
  maxUnavailable: 1
  maxSurge: 1
  
  preDeployChecks:
    - migrations pending check
    - database backup verified
    - rollback procedure documented
    
  postDeployChecks:
    - health endpoint returns 200
    - smoke tests pass
    - error rate < 1%
    
  rollback:
    automatic: true
    trigger:
      - error rate > 5%
      - health check failures >= 3
      - latency p99 > 2s
    procedure: |
      1. Stop new deployment
      2. Scale down new pods
      3. Scale up previous version
      4. Verify health checks
      5. Notify team

# =============================================================================
# SECRETS MANAGEMENT
# =============================================================================

secrets:
  storage: environment-variables
  rotation:
    JWT_SECRET:
      frequency: monthly
      gracePeriod: 7d
    DATABASE_PASSWORD:
      frequency: quarterly
  
  neverLog:
    - JWT_SECRET
    - DATABASE_URL
    - API_KEYS
    - *_PASSWORD
    - *_SECRET

# =============================================================================
# MONITORING
# =============================================================================

monitoring:
  metrics:
    - http_requests_total
    - http_request_duration_seconds
    - database_connections_active
    - database_query_duration_seconds
    
  alerts:
    - name: HighErrorRate
      condition: error_rate > 5%
      severity: critical
      
    - name: SlowResponses
      condition: p99_latency > 2s
      severity: warning
      
    - name: DatabaseConnectionPoolExhausted
      condition: db_connections >= max_connections * 0.9
      severity: critical

  logging:
    format: json
    fields:
      - timestamp
      - level
      - message
      - requestId
      - userId
      - duration
