#!/bin/bash

# create-project.sh - Create a new project in the sandbox by copying base-project structure
# Usage: ./create-project.sh <project-name>
#
# This script creates a local project in sandbox/ for development and testing.
# For production projects, use start_project.sh which creates a GitHub fork.

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BASE_DIR="$(dirname "$SCRIPT_DIR")"
SANDBOX_DIR="$BASE_DIR/sandbox"

# Helper functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[OK]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check for project name argument
if [ -z "$1" ]; then
    log_error "Project name required"
    echo "Usage: ./create-project.sh <project-name>"
    echo ""
    echo "Examples:"
    echo "  ./create-project.sh my-new-app"
    echo "  ./create-project.sh ecommerce-platform"
    exit 1
fi

PROJECT_NAME="$1"
PROJECT_DIR="$SANDBOX_DIR/$PROJECT_NAME"

# Validate project name (alphanumeric, hyphens, underscores only)
if [[ ! "$PROJECT_NAME" =~ ^[a-zA-Z][a-zA-Z0-9_-]*$ ]]; then
    log_error "Invalid project name: $PROJECT_NAME"
    echo "Project name must start with a letter and contain only letters, numbers, hyphens, and underscores"
    exit 1
fi

log_info "Creating project: $PROJECT_NAME"

# Create sandbox directory if not exists
if [ ! -d "$SANDBOX_DIR" ]; then
    log_info "Creating sandbox directory..."
    mkdir -p "$SANDBOX_DIR"
fi

# Check project doesn't already exist
if [ -d "$PROJECT_DIR" ]; then
    log_error "Project already exists at $PROJECT_DIR"
    exit 1
fi

# Generate unique project ID
PROJECT_ID="proj_$(date +%s | shasum | cut -c1-8)"
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

log_info "Copying base-project structure..."

# Copy base-project structure (excluding node_modules, .git, sandbox, etc.)
rsync -a --progress "$BASE_DIR/" "$PROJECT_DIR/" \
    --exclude 'node_modules' \
    --exclude '.git' \
    --exclude 'sandbox' \
    --exclude '*.log' \
    --exclude 'dist' \
    --exclude '.next' \
    --exclude '.turbo' \
    --exclude 'coverage' \
    --exclude '.env' \
    --exclude '.env.local' \
    --exclude '.DS_Store' \
    --exclude '*.tmp' \
    --exclude '*.swp'

log_success "Project files copied"

# Initialize git repo
log_info "Initializing git repository..."
cd "$PROJECT_DIR"
git init --quiet
git add .
git commit -m "Initial commit from base-project template" --quiet

log_success "Git repository initialized"

# Create .project.yaml
log_info "Creating project metadata..."
cat > "$PROJECT_DIR/.project.yaml" << EOF
# Project Metadata
# Generated by create-project.sh
id: "$PROJECT_ID"
name: "$PROJECT_NAME"
slug: "$PROJECT_NAME"
description: "Created from base-project template"

# Timestamps
created_at: "$TIMESTAMP"
updated_at: "$TIMESTAMP"

# Status
status: "active"

# Discovery information
discovery:
  completed: false
  started_at: null
  completed_at: null
  prd_path: ""
  stories_path: ""
  interview:
    questions_asked: 0
    duration_minutes: 0
    key_requirements: []

# Project settings
settings:
  parallel_execution: true
  auto_qa: true
  require_approval: true
  notification_webhook: null

# Source template
source:
  template: "base-project"
  forked_at: "$TIMESTAMP"
  base_commit: "local"

# Stack configuration
stack:
  node_version: "22"
  typescript: true
  database: "postgresql"
  frontend_framework: "react"
  css_framework: "tailwind"
EOF

log_success "Project metadata created"

# Create plans/features directory structure
log_info "Creating feature directory structure..."
mkdir -p "$PROJECT_DIR/plans/features"

# Create feature index
cat > "$PROJECT_DIR/plans/features/.index.yaml" << EOF
# Feature Index
# Generated by create-project.sh
version: "1.0"
updated_at: "$TIMESTAMP"
project_id: "$PROJECT_ID"

# Summary counts
summary:
  total: 0
  planning: 0
  in_progress: 0
  qa: 0
  completed: 0
  archived: 0

# Features by status
by_status:
  planning: []
  in_progress: []
  qa: []
  completed: []
  archived: []

# Features by priority
by_priority:
  high: []
  medium: []
  low: []

# Execution order
execution_order: []

# ID generation
next_feature_id: 1
EOF

log_success "Feature directory structure created"

# Update registry (create if not exists)
REGISTRY_FILE="$SANDBOX_DIR/.registry.yaml"

if [ ! -f "$REGISTRY_FILE" ]; then
    log_info "Creating project registry..."
    cat > "$REGISTRY_FILE" << EOF
# Project Registry
# Tracks all projects in the sandbox
version: "1.0"
updated_at: "$TIMESTAMP"

# Configuration
config:
  auto_cleanup_days: 30
  max_active_projects: 10
  default_branch: "main"

# Registered projects
projects: []

# Next ID counter
next_project_id: 1
EOF
fi

# Add project to registry using a simple append approach
# Note: For production, use a proper YAML parser
log_info "Updating project registry..."

# Create a temporary file with the new project entry
TEMP_ENTRY=$(cat << EOF

  - id: "$PROJECT_ID"
    name: "$PROJECT_NAME"
    path: "sandbox/$PROJECT_NAME"
    status: "active"
    created_at: "$TIMESTAMP"
    updated_at: "$TIMESTAMP"
    discovery:
      completed: false
      prd_generated: false
      tasks_generated: false
      approved_at: null
    metrics:
      features_total: 0
      features_completed: 0
      tasks_total: 0
      tasks_pending: 0
      tasks_in_progress: 0
      tasks_blocked: 0
      tasks_qa: 0
      tasks_completed: 0
    execution:
      mode: "idle"
      current_phase: 0
      current_feature: null
      agents_active: []
    git:
      current_branch: "main"
      has_uncommitted: false
      last_commit: null
EOF
)

# Insert project entry after "projects:" line
if grep -q "^projects: \[\]$" "$REGISTRY_FILE"; then
    # Replace empty projects array with the new entry
    sed -i '' "s/^projects: \[\]$/projects:$TEMP_ENTRY/" "$REGISTRY_FILE"
else
    # Append to existing projects
    # Find the line number of "projects:" and insert after it
    sed -i '' "/^projects:/a\\
$TEMP_ENTRY
" "$REGISTRY_FILE"
fi

# Update registry timestamp
sed -i '' "s/^updated_at:.*/updated_at: \"$TIMESTAMP\"/" "$REGISTRY_FILE"

log_success "Project registry updated"

# Create dashboard aggregation file if not exists
DASHBOARD_FILE="$SANDBOX_DIR/.dashboard.yaml"

if [ ! -f "$DASHBOARD_FILE" ]; then
    log_info "Creating dashboard aggregation file..."
    cat > "$DASHBOARD_FILE" << EOF
# Dashboard Aggregation
# Cross-project metrics for the dashboard UI
version: "1.0"
updated_at: "$TIMESTAMP"
stale_threshold_minutes: 5

# Global totals
totals:
  projects: 1
  projects_active: 1
  projects_paused: 0
  features: 0
  features_in_progress: 0
  tasks_total: 0
  tasks_pending: 0
  tasks_in_progress: 0
  tasks_blocked: 0
  tasks_qa: 0
  tasks_completed: 0

# Active agents
agents_active: []

# Recent activity
recent_activity: []

# Execution queue
queue:
  next_tasks: []

# Health metrics
health:
  last_successful_execution: null
  failed_tasks_24h: 0
  average_task_duration_minutes: 0
  index_last_regenerated: "$TIMESTAMP"
EOF
fi

log_success "Dashboard file ready"

# Create locks file if not exists
LOCKS_FILE="$SANDBOX_DIR/.locks.yaml"

if [ ! -f "$LOCKS_FILE" ]; then
    log_info "Creating locks file..."
    cat > "$LOCKS_FILE" << EOF
# File Locks
# Active file locks for conflict prevention
version: "1.0"
updated_at: "$TIMESTAMP"

# Configuration
config:
  default_ttl_minutes: 30
  max_ttl_minutes: 120
  stale_check_interval_seconds: 60
  auto_release_on_completion: true

# Active locks
locks: []

# Lock history
history: []

# Lock queue
queue: []
EOF
fi

log_success "Locks file ready"

# Final summary
echo ""
echo -e "${GREEN}=======================================================${NC}"
echo -e "${GREEN}  Project '$PROJECT_NAME' created successfully!${NC}"
echo -e "${GREEN}=======================================================${NC}"
echo ""
echo "  Project ID: $PROJECT_ID"
echo "  Location:   $PROJECT_DIR"
echo "  Registry:   $REGISTRY_FILE"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. cd $PROJECT_DIR"
echo "  2. Run /discovery to gather requirements"
echo "  3. Review generated PRD and tasks"
echo "  4. Start execution with /parallel"
echo ""
