#!/bin/bash

# update-registry.sh - Update sandbox/.registry.yaml with project list
# Usage: ./update-registry.sh [--scan] [--add <project-dir>] [--remove <project-name>] [--status <project-name> <status>]
#
# This script manages the project registry file in the sandbox directory.

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BASE_DIR="$(dirname "$SCRIPT_DIR")"
SANDBOX_DIR="$BASE_DIR/sandbox"
REGISTRY_FILE="$SANDBOX_DIR/.registry.yaml"

# Helper functions
log_info() {
    echo -e "${BLUE}[REGISTRY]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[REGISTRY]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[REGISTRY]${NC} $1"
}

log_error() {
    echo -e "${RED}[REGISTRY]${NC} $1"
}

# Parse YAML field
get_yaml_field() {
    local file="$1"
    local field="$2"
    grep "^${field}:" "$file" 2>/dev/null | sed "s/^${field}:[[:space:]]*//" | tr -d '"'
}

# Initialize registry if not exists
init_registry() {
    if [ ! -d "$SANDBOX_DIR" ]; then
        mkdir -p "$SANDBOX_DIR"
    fi

    if [ ! -f "$REGISTRY_FILE" ]; then
        log_info "Creating new registry file..."
        TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        cat > "$REGISTRY_FILE" << EOF
# Project Registry
# Tracks all projects in the sandbox
# Generated by update-registry.sh
version: "1.0"
updated_at: "$TIMESTAMP"

# Configuration
config:
  auto_cleanup_days: 30
  max_active_projects: 10
  default_branch: "main"

# Registered projects
projects: []

# Next ID counter
next_project_id: 1
EOF
        log_success "Registry created at $REGISTRY_FILE"
    fi
}

# Scan sandbox for projects
scan_projects() {
    log_info "Scanning sandbox for projects..."

    init_registry

    local found=0
    local added=0

    for project_dir in "$SANDBOX_DIR"/*/; do
        if [ ! -d "$project_dir" ]; then
            continue
        fi

        local project_name=$(basename "$project_dir")

        # Skip hidden directories
        if [[ "$project_name" == .* ]]; then
            continue
        fi

        local project_file="$project_dir/.project.yaml"
        if [ ! -f "$project_file" ]; then
            log_warn "No .project.yaml in $project_name, skipping"
            continue
        fi

        ((found++))

        local project_id=$(get_yaml_field "$project_file" "id")
        local project_status=$(get_yaml_field "$project_file" "status")

        # Check if already in registry
        if grep -q "name: \"$project_name\"" "$REGISTRY_FILE" 2>/dev/null; then
            log_info "Found: $project_name (already registered)"
        else
            log_info "Found: $project_name (adding to registry)"
            add_project "$project_dir"
            ((added++))
        fi
    done

    # Update timestamp
    TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    sed -i '' "s/^updated_at:.*/updated_at: \"$TIMESTAMP\"/" "$REGISTRY_FILE"

    echo ""
    log_success "Scan complete"
    echo "  Found:   $found project(s)"
    echo "  Added:   $added project(s)"
}

# Add a project to registry
add_project() {
    local project_dir="$1"

    if [ ! -d "$project_dir" ]; then
        log_error "Project directory not found: $project_dir"
        return 1
    fi

    local project_name=$(basename "$project_dir")
    local project_file="$project_dir/.project.yaml"

    if [ ! -f "$project_file" ]; then
        log_error "No .project.yaml found in $project_dir"
        return 1
    fi

    # Check if already registered
    if grep -q "name: \"$project_name\"" "$REGISTRY_FILE" 2>/dev/null; then
        log_warn "Project $project_name already in registry"
        return 0
    fi

    # Get project metadata
    local project_id=$(get_yaml_field "$project_file" "id")
    local project_status=$(get_yaml_field "$project_file" "status")
    local created_at=$(get_yaml_field "$project_file" "created_at")

    if [ -z "$project_id" ]; then
        project_id="proj_$(date +%s | shasum | cut -c1-8)"
    fi

    if [ -z "$project_status" ]; then
        project_status="active"
    fi

    TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

    if [ -z "$created_at" ]; then
        created_at="$TIMESTAMP"
    fi

    # Get metrics from feature index if exists
    local features_total=0
    local features_completed=0
    local tasks_total=0
    local tasks_pending=0
    local tasks_in_progress=0
    local tasks_blocked=0
    local tasks_qa=0
    local tasks_completed=0

    local features_index="$project_dir/plans/features/.index.yaml"
    if [ -f "$features_index" ]; then
        features_total=$(grep "^  total:" "$features_index" 2>/dev/null | head -1 | grep -o '[0-9]*' || echo "0")
        features_completed=$(grep "^  completed:" "$features_index" 2>/dev/null | head -1 | grep -o '[0-9]*' || echo "0")
    fi

    # Count tasks from all features
    for feature_dir in "$project_dir/plans/features"/FEAT-*/; do
        if [ -d "$feature_dir" ]; then
            local feat_index="$feature_dir/index.yaml"
            if [ -f "$feat_index" ]; then
                local ft=$(grep "^  total:" "$feat_index" 2>/dev/null | grep -o '[0-9]*' || echo "0")
                local fp=$(grep "^  pending:" "$feat_index" 2>/dev/null | grep -o '[0-9]*' || echo "0")
                local fi=$(grep "^  in_progress:" "$feat_index" 2>/dev/null | grep -o '[0-9]*' || echo "0")
                local fb=$(grep "^  blocked:" "$feat_index" 2>/dev/null | grep -o '[0-9]*' || echo "0")
                local fq=$(grep "^  qa:" "$feat_index" 2>/dev/null | grep -o '[0-9]*' || echo "0")
                local fc=$(grep "^  completed:" "$feat_index" 2>/dev/null | grep -o '[0-9]*' || echo "0")

                tasks_total=$((tasks_total + ft))
                tasks_pending=$((tasks_pending + fp))
                tasks_in_progress=$((tasks_in_progress + fi))
                tasks_blocked=$((tasks_blocked + fb))
                tasks_qa=$((tasks_qa + fq))
                tasks_completed=$((tasks_completed + fc))
            fi
        fi
    done

    # Build project entry
    local project_entry="  - id: \"$project_id\"
    name: \"$project_name\"
    path: \"sandbox/$project_name\"
    status: \"$project_status\"
    created_at: \"$created_at\"
    updated_at: \"$TIMESTAMP\"
    discovery:
      completed: false
      prd_generated: false
      tasks_generated: false
      approved_at: null
    metrics:
      features_total: $features_total
      features_completed: $features_completed
      tasks_total: $tasks_total
      tasks_pending: $tasks_pending
      tasks_in_progress: $tasks_in_progress
      tasks_blocked: $tasks_blocked
      tasks_qa: $tasks_qa
      tasks_completed: $tasks_completed
    execution:
      mode: \"idle\"
      current_phase: 0
      current_feature: null
      agents_active: []
    git:
      current_branch: \"main\"
      has_uncommitted: false
      last_commit: null"

    # Add to registry
    if grep -q "^projects: \[\]$" "$REGISTRY_FILE"; then
        sed -i '' "s/^projects: \[\]$/projects:\n$project_entry/" "$REGISTRY_FILE"
    else
        sed -i '' "/^projects:/a\\
$project_entry
" "$REGISTRY_FILE"
    fi

    # Update timestamp
    sed -i '' "s/^updated_at:.*/updated_at: \"$TIMESTAMP\"/" "$REGISTRY_FILE"

    log_success "Added project: $project_name"
}

# Remove a project from registry
remove_project() {
    local project_name="$1"

    if [ -z "$project_name" ]; then
        log_error "Project name required"
        return 1
    fi

    if ! grep -q "name: \"$project_name\"" "$REGISTRY_FILE" 2>/dev/null; then
        log_warn "Project $project_name not found in registry"
        return 0
    fi

    log_info "Removing project: $project_name"

    # Use awk to remove the project entry
    # This handles multi-line YAML entries
    TEMP_FILE=$(mktemp)
    trap "rm -f $TEMP_FILE" EXIT

    awk '
        BEGIN { skip = 0; in_projects = 0 }
        /^projects:/ { in_projects = 1; print; next }
        /^[a-z]/ && !/^  / { in_projects = 0; skip = 0 }
        /^  - id:/ && in_projects { skip = 0 }
        /name: "'"$project_name"'"/ && in_projects { skip = 1 }
        !skip { print }
    ' "$REGISTRY_FILE" > "$TEMP_FILE"

    mv "$TEMP_FILE" "$REGISTRY_FILE"

    # Update timestamp
    TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    sed -i '' "s/^updated_at:.*/updated_at: \"$TIMESTAMP\"/" "$REGISTRY_FILE"

    log_success "Removed project: $project_name"
}

# Update project status
update_status() {
    local project_name="$1"
    local new_status="$2"

    if [ -z "$project_name" ] || [ -z "$new_status" ]; then
        log_error "Project name and status required"
        return 1
    fi

    # Validate status
    case "$new_status" in
        "active"|"paused"|"archived"|"failed")
            ;;
        *)
            log_error "Invalid status: $new_status"
            echo "Valid statuses: active | paused | archived | failed"
            return 1
            ;;
    esac

    if ! grep -q "name: \"$project_name\"" "$REGISTRY_FILE" 2>/dev/null; then
        log_error "Project $project_name not found in registry"
        return 1
    fi

    log_info "Updating $project_name status to $new_status"

    # This is a simplified approach - in production use a YAML parser
    # Find the project section and update its status
    TEMP_FILE=$(mktemp)
    trap "rm -f $TEMP_FILE" EXIT

    awk -v name="$project_name" -v status="$new_status" '
        BEGIN { in_project = 0 }
        /name: "/ {
            if (index($0, name) > 0) {
                in_project = 1
            } else {
                in_project = 0
            }
        }
        /^    status:/ && in_project {
            gsub(/status: "[^"]*"/, "status: \"" status "\"")
        }
        { print }
    ' "$REGISTRY_FILE" > "$TEMP_FILE"

    mv "$TEMP_FILE" "$REGISTRY_FILE"

    # Also update the project's .project.yaml
    local project_file="$SANDBOX_DIR/$project_name/.project.yaml"
    if [ -f "$project_file" ]; then
        sed -i '' "s/^status:.*/status: \"$new_status\"/" "$project_file"
    fi

    # Update timestamp
    TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    sed -i '' "s/^updated_at:.*/updated_at: \"$TIMESTAMP\"/" "$REGISTRY_FILE"

    log_success "Updated $project_name status to $new_status"
}

# List all projects
list_projects() {
    init_registry

    log_info "Registered projects:"
    echo ""

    if grep -q "^projects: \[\]$" "$REGISTRY_FILE"; then
        echo "  No projects registered"
        return
    fi

    # Extract and display project info
    grep -A 4 "^  - id:" "$REGISTRY_FILE" | while read -r line; do
        if echo "$line" | grep -q "name:"; then
            local name=$(echo "$line" | sed 's/.*name: "//' | tr -d '"')
            echo -n "  - $name"
        fi
        if echo "$line" | grep -q "status:"; then
            local status=$(echo "$line" | sed 's/.*status: "//' | tr -d '"')
            case "$status" in
                "active") echo -e " ${GREEN}[$status]${NC}" ;;
                "paused") echo -e " ${YELLOW}[$status]${NC}" ;;
                "archived") echo -e " ${BLUE}[$status]${NC}" ;;
                "failed") echo -e " ${RED}[$status]${NC}" ;;
                *) echo " [$status]" ;;
            esac
        fi
    done
}

# Show usage
show_usage() {
    echo "Usage: ./update-registry.sh [OPTION]"
    echo ""
    echo "Options:"
    echo "  --scan                     Scan sandbox and sync registry"
    echo "  --add <project-dir>        Add a project to registry"
    echo "  --remove <project-name>    Remove a project from registry"
    echo "  --status <name> <status>   Update project status"
    echo "  --list                     List all registered projects"
    echo "  --help                     Show this help message"
    echo ""
    echo "Status values: active | paused | archived | failed"
    echo ""
    echo "Examples:"
    echo "  ./update-registry.sh --scan"
    echo "  ./update-registry.sh --add sandbox/my-project"
    echo "  ./update-registry.sh --status my-project paused"
    echo "  ./update-registry.sh --list"
}

# Main logic
case "$1" in
    "--scan")
        scan_projects
        ;;
    "--add")
        init_registry
        add_project "$2"
        ;;
    "--remove")
        init_registry
        remove_project "$2"
        ;;
    "--status")
        init_registry
        update_status "$2" "$3"
        ;;
    "--list")
        list_projects
        ;;
    "--help"|"-h"|"")
        show_usage
        ;;
    *)
        log_error "Unknown option: $1"
        show_usage
        exit 1
        ;;
esac
